#!/usr/bin/env node
/**
 * Generates src/data/timings.ts from the derived per-section timing JSONs in
 * scripts/timings/. Run after re-deriving timings with scripts/timing/timing.py
 * or scripts/timing/timing_ao.py.
 *
 *   node scripts/build-timings.mjs
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const timingDir = join(here, 'timings');
const outFile = join(here, '..', 'src', 'data', 'timings.ts');

const SECTION_ORDER = [
  'verse-1',
  'pre-chorus-1',
  'chorus-1',
  'verse-2',
  'pre-chorus-2',
  'bridge',
  'final-chorus',
  'outro',
];

const available = new Set(
  readdirSync(timingDir)
    .filter((f) => f.endsWith('.json'))
    .map((f) => f.replace(/\.json$/, '')),
);

for (const id of SECTION_ORDER) {
  if (!available.has(id)) throw new Error(`missing timing for section "${id}"`);
}

const round = (n) => Math.round(n * 1000) / 1000;

const entries = SECTION_ORDER.map((id) => {
  const raw = JSON.parse(readFileSync(join(timingDir, `${id}.json`), 'utf8'));
  const lines = [];
  for (const line of raw.lines) {
    const syllables = raw.notes.filter((n) => n.line === line.line);
    lines.push({
      start: round(line.span[0]),
      end: round(line.span[1]),
      syllables: syllables.map((s) => ({ start: s.start, end: s.end })),
    });
  }
  return {
    id,
    duration: raw.audio_duration,
    lines,
  };
});

let offset = 0;
for (const e of entries) {
  e.songOffset = round(offset);
  offset += e.duration;
}
const fullDuration = round(offset);

const body = entries
  .map((e) => {
    const lines = e.lines
      .map((l) => {
        const syls = l.syllables.map((s) => `{ start: ${s.start}, end: ${s.end} }`).join(', ');
        return `      { start: ${l.start}, end: ${l.end}, syllables: [${syls}] },`;
      })
      .join('\n');
    return `  '${e.id}': {
    songOffset: ${e.songOffset},
    duration: ${e.duration},
    lines: [
${lines}
    ],
  },`;
  })
  .join('\n');

const ts = `// GENERATED by scripts/build-timings.mjs — do not edit by hand.
// Derived from the guide-vocal audio (see scripts/timing/). Regenerate with:
//   node scripts/build-timings.mjs

export interface SyllableTiming {
  start: number;
  end: number;
}

export interface LineTiming {
  start: number;
  end: number;
  syllables: SyllableTiming[];
}

export interface SectionTiming {
  /** Start of this section inside the full-song guide vocal, in seconds. */
  songOffset: number;
  /** Duration of this section's audio file, in seconds. */
  duration: number;
  lines: LineTiming[];
}

/** Song order. Section ids in the order the song plays. */
export const SECTION_ORDER = [
${SECTION_ORDER.map((id) => `  '${id}',`).join('\n')}
] as const;

/** Section id -> absolute syllable timings, relative to that section's audio. */
export const SECTION_TIMINGS: Record<string, SectionTiming> = {
${body}
};

/** Total duration of the full-song guide vocal, in seconds. */
export const FULL_SONG_DURATION = ${fullDuration};
`;

writeFileSync(outFile, ts);
console.log(
  `wrote ${outFile}\n  ${entries.length} sections, ${fullDuration}s total, ` +
    `${entries.reduce((n, e) => n + e.lines.reduce((m, l) => m + l.syllables.length, 0), 0)} syllables`,
);
