// GENERATED by scripts/build-timings.mjs — do not edit by hand.
// Derived from the guide-vocal audio (see scripts/timing/). Regenerate with:
//   node scripts/build-timings.mjs

export interface SyllableTiming {
  start: number;
  end: number;
}

export interface LineTiming {
  start: number;
  end: number;
  syllables: SyllableTiming[];
}

export interface SectionTiming {
  /** Start of this section inside the full-song guide vocal, in seconds. */
  songOffset: number;
  /** Duration of this section's audio file, in seconds. */
  duration: number;
  lines: LineTiming[];
}

/** Song order. Section ids in the order the song plays. */
export const SECTION_ORDER = [
  'verse-1',
  'pre-chorus-1',
  'chorus-1',
  'verse-2',
  'pre-chorus-2',
  'bridge',
  'final-chorus',
  'outro',
] as const;

/** Section id -> absolute syllable timings, relative to that section's audio. */
export const SECTION_TIMINGS: Record<string, SectionTiming> = {
  'verse-1': {
    songOffset: 0,
    duration: 28.788,
    lines: [
      { start: 0, end: 4.555, syllables: [{ start: 0.058, end: 0.348 }, { start: 0.348, end: 0.557 }, { start: 0.557, end: 1.103 }, { start: 1.103, end: 1.312 }, { start: 1.312, end: 1.73 }, { start: 1.73, end: 2.276 }, { start: 2.276, end: 2.821 }, { start: 2.821, end: 2.972 }, { start: 2.972, end: 3.518 }, { start: 3.518, end: 4.555 }] },
      { start: 5.254, end: 8.406, syllables: [{ start: 5.312, end: 5.602 }, { start: 5.602, end: 5.706 }, { start: 5.706, end: 5.962 }, { start: 5.962, end: 6.252 }, { start: 6.252, end: 6.438 }, { start: 6.438, end: 6.624 }, { start: 6.624, end: 6.867 }, { start: 6.867, end: 7.343 }, { start: 7.343, end: 7.634 }, { start: 7.634, end: 8.406 }] },
      { start: 9.056, end: 12.86, syllables: [{ start: 9.183, end: 9.264 }, { start: 9.264, end: 9.775 }, { start: 9.775, end: 10.089 }, { start: 10.089, end: 10.379 }, { start: 10.379, end: 10.762 }, { start: 10.762, end: 11.064 }, { start: 11.064, end: 11.366 }, { start: 11.366, end: 12.86 }] },
      { start: 13.813, end: 18.345, syllables: [{ start: 13.871, end: 14.162 }, { start: 14.162, end: 14.382 }, { start: 14.382, end: 14.603 }, { start: 14.603, end: 14.881 }, { start: 14.881, end: 15.566 }, { start: 15.566, end: 16.124 }, { start: 16.124, end: 16.588 }, { start: 16.588, end: 16.809 }, { start: 16.809, end: 17.273 }, { start: 17.273, end: 18.345 }] },
      { start: 19.006, end: 22.818, syllables: [{ start: 19.064, end: 19.366 }, { start: 19.366, end: 19.633 }, { start: 19.633, end: 19.784 }, { start: 19.784, end: 20.062 }, { start: 20.062, end: 20.271 }, { start: 20.271, end: 20.782 }, { start: 20.782, end: 21.061 }, { start: 21.061, end: 21.525 }, { start: 21.525, end: 21.723 }, { start: 21.723, end: 22.818 }] },
      { start: 23.578, end: 28.788, syllables: [{ start: 23.636, end: 23.926 }, { start: 23.926, end: 24.193 }, { start: 24.193, end: 24.622 }, { start: 24.622, end: 25.064 }, { start: 25.064, end: 25.667 }, { start: 25.667, end: 25.818 }, { start: 25.818, end: 26.352 }, { start: 26.352, end: 26.875 }, { start: 26.875, end: 27.374 }, { start: 27.374, end: 28.788 }] },
    ],
  },
  'pre-chorus-1': {
    songOffset: 28.788,
    duration: 13.895,
    lines: [
      { start: 0, end: 2.644, syllables: [{ start: 0.058, end: 0.209 }, { start: 0.209, end: 0.72 }, { start: 0.72, end: 0.964 }, { start: 0.964, end: 1.08 }, { start: 1.08, end: 1.428 }, { start: 1.428, end: 1.695 }, { start: 1.695, end: 2.148 }, { start: 2.148, end: 2.644 }] },
      { start: 3.158, end: 5.622, syllables: [{ start: 3.228, end: 3.437 }, { start: 3.437, end: 3.866 }, { start: 3.866, end: 3.971 }, { start: 3.971, end: 4.087 }, { start: 4.087, end: 4.377 }, { start: 4.377, end: 4.911 }, { start: 4.911, end: 5.622 }] },
      { start: 6.311, end: 9.412, syllables: [{ start: 6.369, end: 6.566 }, { start: 6.566, end: 7.054 }, { start: 7.054, end: 7.332 }, { start: 7.332, end: 7.739 }, { start: 7.739, end: 8.052 }, { start: 8.052, end: 8.389 }, { start: 8.389, end: 8.807 }, { start: 8.807, end: 9.412 }] },
      { start: 9.826, end: 13.895, syllables: [{ start: 9.908, end: 10.012 }, { start: 10.012, end: 10.535 }, { start: 10.535, end: 10.779 }, { start: 10.779, end: 11.22 }, { start: 11.22, end: 12.207 }, { start: 12.207, end: 12.624 }, { start: 12.624, end: 13.895 }] },
    ],
  },
  'chorus-1': {
    songOffset: 42.683,
    duration: 28.328,
    lines: [
      { start: 0, end: 2.645, syllables: [{ start: 0.058, end: 0.325 }, { start: 0.325, end: 0.65 }, { start: 0.65, end: 0.871 }, { start: 0.871, end: 0.987 }, { start: 0.987, end: 1.37 }, { start: 1.37, end: 1.962 }, { start: 1.962, end: 2.183 }, { start: 2.183, end: 2.645 }] },
      { start: 3.371, end: 5.976, syllables: [{ start: 3.429, end: 3.545 }, { start: 3.545, end: 3.754 }, { start: 3.754, end: 4.056 }, { start: 4.056, end: 4.578 }, { start: 4.578, end: 4.776 }, { start: 4.776, end: 5.976 }] },
      { start: 7.111, end: 10.015, syllables: [{ start: 7.169, end: 7.448 }, { start: 7.448, end: 7.657 }, { start: 7.657, end: 7.901 }, { start: 7.901, end: 7.993 }, { start: 7.993, end: 8.493 }, { start: 8.493, end: 8.957 }, { start: 8.957, end: 9.154 }, { start: 9.154, end: 10.015 }] },
      { start: 10.541, end: 13.072, syllables: [{ start: 10.599, end: 10.866 }, { start: 10.866, end: 11.424 }, { start: 11.424, end: 11.586 }, { start: 11.586, end: 11.911 }, { start: 11.911, end: 12.097 }, { start: 12.097, end: 13.072 }] },
      { start: 13.902, end: 16.872, syllables: [{ start: 13.96, end: 14.238 }, { start: 14.238, end: 14.772 }, { start: 14.772, end: 15.248 }, { start: 15.248, end: 15.55 }, { start: 15.55, end: 15.829 }, { start: 15.829, end: 16.293 }, { start: 16.293, end: 16.872 }] },
      { start: 17.314, end: 20.385, syllables: [{ start: 17.372, end: 17.569 }, { start: 17.569, end: 18.022 }, { start: 18.022, end: 18.254 }, { start: 18.254, end: 18.707 }, { start: 18.707, end: 19.009 }, { start: 19.009, end: 19.276 }, { start: 19.276, end: 20.385 }] },
      { start: 21.069, end: 24.23, syllables: [{ start: 21.127, end: 21.498 }, { start: 21.498, end: 21.684 }, { start: 21.684, end: 22.137 }, { start: 22.137, end: 22.45 }, { start: 22.45, end: 22.682 }, { start: 22.682, end: 23.135 }, { start: 23.135, end: 23.808 }, { start: 23.808, end: 24.23 }] },
      { start: 24.617, end: 28.328, syllables: [{ start: 24.675, end: 24.837 }, { start: 24.837, end: 25.023 }, { start: 25.023, end: 25.975 }, { start: 25.975, end: 26.207 }, { start: 26.207, end: 26.567 }, { start: 26.567, end: 26.695 }, { start: 26.695, end: 28.328 }] },
    ],
  },
  'verse-2': {
    songOffset: 71.011,
    duration: 29.395,
    lines: [
      { start: 0, end: 4.123, syllables: [{ start: 0.058, end: 0.534 }, { start: 0.534, end: 0.697 }, { start: 0.697, end: 1.08 }, { start: 1.08, end: 1.811 }, { start: 1.811, end: 2.078 }, { start: 2.078, end: 2.496 }, { start: 2.496, end: 2.844 }, { start: 2.844, end: 3.553 }, { start: 3.553, end: 3.692 }, { start: 3.692, end: 4.123 }] },
      { start: 4.935, end: 9.049, syllables: [{ start: 4.993, end: 5.376 }, { start: 5.376, end: 5.585 }, { start: 5.585, end: 6.015 }, { start: 6.015, end: 6.618 }, { start: 6.618, end: 7.083 }, { start: 7.083, end: 7.35 }, { start: 7.35, end: 7.64 }, { start: 7.64, end: 8.163 }, { start: 8.163, end: 8.581 }, { start: 8.581, end: 9.049 }] },
      { start: 9.916, end: 14.481, syllables: [{ start: 9.974, end: 10.322 }, { start: 10.322, end: 10.995 }, { start: 10.995, end: 11.286 }, { start: 11.286, end: 12.005 }, { start: 12.005, end: 12.226 }, { start: 12.226, end: 12.714 }, { start: 12.714, end: 13.155 }, { start: 13.155, end: 13.759 }, { start: 13.759, end: 14.037 }, { start: 14.037, end: 14.481 }] },
      { start: 15.523, end: 19.503, syllables: [{ start: 15.581, end: 15.895 }, { start: 15.895, end: 16.359 }, { start: 16.359, end: 16.603 }, { start: 16.603, end: 16.847 }, { start: 16.847, end: 17.288 }, { start: 17.288, end: 17.601 }, { start: 17.601, end: 18.043 }, { start: 18.043, end: 18.402 }, { start: 18.402, end: 18.728 }, { start: 18.728, end: 19.157 }, { start: 19.157, end: 19.503 }] },
      { start: 20.133, end: 25.181, syllables: [{ start: 20.33, end: 20.423 }, { start: 20.423, end: 20.818 }, { start: 20.818, end: 21.305 }, { start: 21.305, end: 21.932 }, { start: 21.932, end: 22.153 }, { start: 22.153, end: 22.664 }, { start: 22.664, end: 22.942 }, { start: 22.942, end: 23.36 }, { start: 23.36, end: 23.906 }, { start: 23.906, end: 24.208 }, { start: 24.208, end: 24.8 }, { start: 24.8, end: 25.181 }] },
      { start: 25.505, end: 29.395, syllables: [{ start: 25.574, end: 25.841 }, { start: 25.841, end: 26.225 }, { start: 26.225, end: 26.933 }, { start: 26.933, end: 27.235 }, { start: 27.235, end: 27.629 }, { start: 27.629, end: 27.989 }, { start: 27.989, end: 28.21 }, { start: 28.21, end: 28.361 }, { start: 28.361, end: 29.395 }] },
    ],
  },
  'pre-chorus-2': {
    songOffset: 100.406,
    duration: 14.544,
    lines: [
      { start: 0, end: 2.719, syllables: [{ start: 0.058, end: 0.418 }, { start: 0.418, end: 0.813 }, { start: 0.813, end: 1.463 }, { start: 1.463, end: 1.66 }, { start: 1.66, end: 2.09 }, { start: 2.09, end: 2.719 }] },
      { start: 3.493, end: 6.665, syllables: [{ start: 3.667, end: 3.818 }, { start: 3.818, end: 4.213 }, { start: 4.213, end: 4.898 }, { start: 4.898, end: 4.979 }, { start: 4.979, end: 5.328 }, { start: 5.328, end: 5.966 }, { start: 5.966, end: 6.164 }, { start: 6.164, end: 6.665 }] },
      { start: 7.382, end: 9.66, syllables: [{ start: 7.44, end: 7.741 }, { start: 7.741, end: 8.067 }, { start: 8.067, end: 8.357 }, { start: 8.357, end: 8.752 }, { start: 8.752, end: 9.065 }, { start: 9.065, end: 9.262 }, { start: 9.262, end: 9.66 }] },
      { start: 10.389, end: 14.544, syllables: [{ start: 10.54, end: 10.899 }, { start: 10.899, end: 11.48 }, { start: 11.48, end: 11.701 }, { start: 11.701, end: 12.142 }, { start: 12.142, end: 12.838 }, { start: 12.838, end: 13.163 }, { start: 13.163, end: 13.639 }, { start: 13.639, end: 13.848 }, { start: 13.848, end: 14.544 }] },
    ],
  },
  'bridge': {
    songOffset: 114.95,
    duration: 25.593,
    lines: [
      { start: 0, end: 3.97, syllables: [{ start: 0.058, end: 0.197 }, { start: 0.197, end: 0.453 }, { start: 0.453, end: 0.801 }, { start: 0.801, end: 1.01 }, { start: 1.01, end: 1.428 }, { start: 1.428, end: 1.718 }, { start: 1.718, end: 2.136 }, { start: 2.136, end: 2.473 }, { start: 2.473, end: 2.682 }, { start: 2.682, end: 3.97 }] },
      { start: 4.606, end: 8.932, syllables: [{ start: 4.665, end: 4.827 }, { start: 4.827, end: 5.094 }, { start: 5.094, end: 5.686 }, { start: 5.686, end: 6.464 }, { start: 6.464, end: 7.056 }, { start: 7.056, end: 7.323 }, { start: 7.323, end: 7.497 }, { start: 7.497, end: 7.706 }, { start: 7.706, end: 8.932 }] },
      { start: 9.528, end: 12.891, syllables: [{ start: 9.586, end: 9.853 }, { start: 9.853, end: 10.086 }, { start: 10.086, end: 10.318 }, { start: 10.318, end: 10.527 }, { start: 10.527, end: 10.863 }, { start: 10.863, end: 11.374 }, { start: 11.374, end: 11.688 }, { start: 11.688, end: 11.873 }, { start: 11.873, end: 12.891 }] },
      { start: 13.349, end: 16.271, syllables: [{ start: 13.418, end: 13.569 }, { start: 13.569, end: 13.825 }, { start: 13.825, end: 14.115 }, { start: 14.115, end: 14.765 }, { start: 14.765, end: 14.974 }, { start: 14.974, end: 15.241 }, { start: 15.241, end: 16.271 }] },
      { start: 17.146, end: 19.507, syllables: [{ start: 17.204, end: 17.355 }, { start: 17.355, end: 17.611 }, { start: 17.611, end: 17.785 }, { start: 17.785, end: 18.191 }, { start: 18.191, end: 18.296 }, { start: 18.296, end: 18.83 }, { start: 18.83, end: 19.507 }] },
      { start: 20.136, end: 25.593, syllables: [{ start: 20.205, end: 20.31 }, { start: 20.31, end: 20.89 }, { start: 20.89, end: 21.064 }, { start: 21.064, end: 21.54 }, { start: 21.54, end: 21.622 }, { start: 21.622, end: 22.249 }, { start: 22.249, end: 24.234 }, { start: 24.234, end: 24.466 }, { start: 24.466, end: 25.593 }] },
    ],
  },
  'final-chorus': {
    songOffset: 140.543,
    duration: 28.361,
    lines: [
      { start: 0, end: 2.645, syllables: [{ start: 0.058, end: 0.325 }, { start: 0.325, end: 0.65 }, { start: 0.65, end: 0.987 }, { start: 0.987, end: 1.37 }, { start: 1.37, end: 1.672 }, { start: 1.672, end: 1.962 }, { start: 1.962, end: 2.368 }, { start: 2.368, end: 2.645 }] },
      { start: 3.371, end: 5.976, syllables: [{ start: 3.429, end: 3.754 }, { start: 3.754, end: 4.056 }, { start: 4.056, end: 4.776 }, { start: 4.776, end: 4.915 }, { start: 4.915, end: 5.414 }, { start: 5.414, end: 5.976 }] },
      { start: 7.111, end: 10.015, syllables: [{ start: 7.169, end: 7.448 }, { start: 7.448, end: 7.901 }, { start: 7.901, end: 7.993 }, { start: 7.993, end: 8.493 }, { start: 8.493, end: 8.957 }, { start: 8.957, end: 9.154 }, { start: 9.154, end: 9.63 }, { start: 9.63, end: 10.015 }] },
      { start: 10.635, end: 13.112, syllables: [{ start: 10.693, end: 11.111 }, { start: 11.111, end: 11.598 }, { start: 11.598, end: 11.947 }, { start: 11.947, end: 12.144 }, { start: 12.144, end: 12.597 }, { start: 12.597, end: 13.112 }] },
      { start: 13.942, end: 16.912, syllables: [{ start: 14, end: 14.278 }, { start: 14.278, end: 14.813 }, { start: 14.813, end: 15.289 }, { start: 15.289, end: 15.59 }, { start: 15.59, end: 16.02 }, { start: 16.02, end: 16.333 }, { start: 16.333, end: 16.912 }] },
      { start: 17.354, end: 20.219, syllables: [{ start: 17.412, end: 17.749 }, { start: 17.749, end: 18.062 }, { start: 18.062, end: 18.782 }, { start: 18.782, end: 19.038 }, { start: 19.038, end: 19.467 }, { start: 19.467, end: 19.653 }, { start: 19.653, end: 20.219 }] },
      { start: 20.812, end: 23.973, syllables: [{ start: 20.87, end: 21.241 }, { start: 21.241, end: 21.427 }, { start: 21.427, end: 21.88 }, { start: 21.88, end: 22.193 }, { start: 22.193, end: 22.878 }, { start: 22.878, end: 23.122 }, { start: 23.122, end: 23.552 }, { start: 23.552, end: 23.973 }] },
      { start: 24.476, end: 25.981, syllables: [{ start: 24.534, end: 24.987 }, { start: 24.987, end: 25.602 }, { start: 25.602, end: 25.981 }] },
      { start: 26.297, end: 28.361, syllables: [{ start: 26.355, end: 26.819 }, { start: 26.819, end: 27.237 }, { start: 27.237, end: 27.319 }, { start: 27.319, end: 28.361 }] },
    ],
  },
  'outro': {
    songOffset: 168.904,
    duration: 7.252,
    lines: [
      { start: 0, end: 2.263, syllables: [{ start: 0.058, end: 0.255 }, { start: 0.255, end: 0.464 }, { start: 0.464, end: 0.673 }, { start: 0.673, end: 2.263 }] },
      { start: 3.196, end: 7.252, syllables: [{ start: 3.254, end: 3.475 }, { start: 3.475, end: 3.73 }, { start: 3.73, end: 3.939 }, { start: 3.939, end: 4.276 }, { start: 4.276, end: 4.74 }, { start: 4.74, end: 5.367 }, { start: 5.367, end: 7.252 }] },
    ],
  },
};

/** Total duration of the full-song guide vocal, in seconds. */
export const FULL_SONG_DURATION = 176.156;
